server:
  port: 7001


eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
    #localhost
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false      #要不要去注册中心获取其他服务的地址
    service-url:
    #集群指向其它eureka
#      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    #单机就是7001自己
      defaultZone: http://eureka7001.com:7001/eureka/
  #server:
    #关闭自我保护机制，保证不可用服务被及时踢除
    #enable-self-preservation: false
    #eviction-interval-timer-in-ms: 2000